### ISSUE TITLE
Content Item component

### ISSUE THREAD

**Issue by halocline** [hpe-design/aries#114]
Component supporting:
Row with Image, Heading, Paragraph

![Screen Shot 2019-12-16 at 2 57 11 PM](https://user-images.githubusercontent.com/1756948/70946775-0942db80-2015-11ea-816c-9e2280f63a11.png)

**Comment by ShimiSun** [comment]
I created an issue last week that is called `Identifier` with the same semantics.

**Comment by halocline** [comment]
Okay. I read the description of that issue, but did not takeaway that it would apply to this treatment as well. 

Confirming that you see this as duplicative? Or as an opportunity to leverage `Identifier`?

I will stop this work since you have that in progress.

**Comment by halocline** [comment]
Duplicate issue.
