### ISSUE TITLE
Consolidate project-script with grommet to affect aries and hpe-server.

### ISSUE THREAD

**Issue by ShimiSun** [hpe-design/aries#12]
https://github.com/HewlettPackard/hpe-js-project-scripts/pull/7
https://github.com/HewlettPackard/hpe-js-project-scripts/pull/8

**Comment by MikeWalrath** [comment]
@ShimiSun Good to close?

**Comment by ShimiSun** [comment]
@MikeWalrath, yes, good catch, the PRs got merged.
