### ISSUE TITLE
Apply active state to sidebar nav

### ISSUE THREAD

**Issue by halocline** [hpe-design/aries#184]
Sidebar nav item should have bold treatment when item is the current page viewed.

**Comment by halocline** [comment]
@taysea I noticed that in the production build, the active state of the anchor does not maintain the bold treatment.
![Screen Shot 2020-01-21 at 1 08 03 PM](https://user-images.githubusercontent.com/1756948/72839210-13c54600-3c4f-11ea-9d4b-ad866eb8f01e.png)

**Comment by taysea** [comment]
Thanks for noticing that, let me look into this.

**Comment by taysea** [comment]
Linking to #270
