### ISSUE TITLE
Aries Site Theme

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/aries#21]

**Comment by halocline** [comment]
- [ ] Inventory color namespace usage in Grommet
- [ ] Headings
- [ ] Text
- [ ] Paragraph
- [ ] Nav background
- [ ] Anchors
- [ ]

**Comment by halocline** [comment]
Moving anchor work to separate issue (https://github.com/hpe-design/aries/issues/69), so that this one can be closed.
