### ISSUE TITLE
Improve "coming soon" delivery

### ISSUE THREAD

**Issue by karatechops** [hpe-design/aries#250]
Can we add more personalized copy to each coming soon page, example below:

![Screen Shot 2020-01-17 at 5 15 02 PM](https://user-images.githubusercontent.com/5983843/72649964-05c0ae00-394d-11ea-8fdf-99b047a48244.png)

Another option could be a generic empty page fallback -
![Screen Shot 2020-01-17 at 5 17 46 PM](https://user-images.githubusercontent.com/5983843/72650086-5c2dec80-394d-11ea-97d7-946118a2c6fc.png)

Anything but "Coming soon!" 😁

**Comment by L0ZZI** [comment]
Put a little more design to it on Figma.
