### ISSUE TITLE
Routing Page Layout - Firefox

### ISSUE THREAD

**Issue by halocline** [hpe-design/aries#289]
![Screen Shot 2020-01-24 at 8 37 28 AM](https://user-images.githubusercontent.com/1756948/73081482-ebbf2800-3e84-11ea-8e60-37bf0f54545f.png)
![Screen Shot 2020-01-24 at 8 37 33 AM](https://user-images.githubusercontent.com/1756948/73081492-eeba1880-3e84-11ea-9044-b99a31ffbcb2.png)

**Comment by taysea** [comment]
Closed by #291
