### ISSUE TITLE
Consolidate monorepo dependencies

### ISSUE THREAD

**Issue by ShimiSun** [hpe-design/aries#3]

**Comment by halocline** [comment]
Here are my findings when researching how to use a git repo as a dependency:
- Super easy with `yarn add [url-to-git-repo.git][#branch/tag/commit]` -- Yay!!!

However, attempting to apply the same approach to a package within a monorepo is not so easy -- Boo... :(
- Threads related to feature requests to both npm and yarn to support monorepo dependencies:
  - [Allow subdirectories within git repos in yarn install](https://github.com/yarnpkg/yarn/issues/4725)
  - [Allow subdirectories within git repos in npm install](https://github.com/yarnpkg/yarn/issues/4725)
- Potential workaround which was [successful for others](https://github.com/ramasilveyra/gitpkg), however, though clever, it seems a hacky...

I think we will need to consider other approaches.
