### ISSUE TITLE
Building Header Component

### ISSUE THREAD

**Issue by ShimiSun** [hpe-design/aries#4]

**Comment by ShimiSun** [comment]
Can we close this issue since we have the Grommet Header component now? or does this issue includes more than that?

**Comment by halocline** [comment]
I think we can close it.

Here is the design which was shared earlier today.
![Screen Shot 2019-12-11 at 5 02 17 PM](https://user-images.githubusercontent.com/1756948/70671102-21db7c00-1c38-11ea-90c5-a5ac9e1fa60e.png)
