### ISSUE TITLE
SEO 

### ISSUE THREAD

**Issue by MikeWalrath** [hpe-design/aries#51]
- [x] Meta tags
  - [x] Page title
  - [x] Page description
  - [x] ~Keywords~ (latest commentary recommends not including keywords)
  - [x] Social
    - [x] OpenGraph
    - [x] Twitter
    - [x ] LinkedIn
      - Per [this article](https://www.linkedin.com/help/linkedin/answer/46687/making-your-website-shareable-on-linkedin?lang=en), LinkedIn is using Open Graph tags which are covered above.
  - [x] HPE Marketing tags?
  - [x] Canonical tags if applicable

**Comment by halocline** [comment]
@MikeWalrath Meta tags for Twitter include a tag which contains the Twitter handle / account associated. Do you know what that handle will be for Aries?

**Comment by halocline** [comment]
@MikeWalrath Also, in the meta tags we add some tags for corporate marketing analytics, however I am unsure as to which specific tags and the values they'd like.

The values on the hpe.design site are the following:

- segment = corporate
- lifecycle = support
- page_content = products
- bu = CORP

I will plan on mimicking these values. Please let me know if others are needed and/or the values should be something else.

**Comment by MikeWalrath** [comment]
@halocline Im not sure we will have a twitter handle. I dont know if it makes much sense at the moment. Yes plese duplicate what has been done on the DEV/Design pages. We can update them if those values have changed.
