### ISSUE TITLE
Home Page

### ISSUE THREAD

**Issue by halocline** [hpe-design/aries#65]
<img width="1213" alt="Screen Shot 2019-12-13 at 1 19 07 PM" src="https://user-images.githubusercontent.com/1756948/70829510-31c79d00-1dab-11ea-98cc-5fb9355ff358.png">

**Comment by ShimiSun** [comment]
Does it mean the landing page? do we have designs for it?

**Comment by halocline** [comment]
Yes, home = landing page.
There is an early design we could work from. Work would include:
- [ ] layout w/ no sidebar
- [ ] content section with background image
- [ ] content foreground image
- [ ] copy
- [ ] button routed to /start

![Screen Shot 2019-11-27 at 11 14 31 AM](https://user-images.githubusercontent.com/1756948/69749340-8b6f6c80-1107-11ea-884c-faf89e79edf8.png)
