### ISSUE TITLE
Bug - Focus is cutoff on Anchors and Buttons

### ISSUE THREAD

**Issue by halocline** [hpe-design/aries#91]
![Screen Shot 2019-12-11 at 9 55 52 AM](https://user-images.githubusercontent.com/1756948/70642896-4cf4aa00-1bfd-11ea-83b8-78932126d2e7.png)

**Comment by ShimiSun** [comment]
the AnchorGroup might need a little `margin` here.

**Comment by halocline** [comment]
Applies to `<Button />` as well, and margin would push these out of alignment with the text, so I wonder if we should add a small amount of horizontal padding to `<MainContent />`... thoughts?

![Screen Shot 2019-12-12 at 4 39 00 PM](https://user-images.githubusercontent.com/1756948/70757732-f0c57f00-1cfd-11ea-8fac-eeb8b82230c2.png)

**Comment by taysea** [comment]
I think adding padding makes sense, but we will need to make sure the on mobile the content will align flush with the HPE logo since the sidebar will be gone
